feature: Resolve filter ordinals
babylonlabs-io/simple-staking pull request #258
Opened 2024-10-25 17:46 UTC by gbarkhatov

- `main` branch uses a combination of non-invasive changes to show the filter ordinals
- `dev` branch uses hooks

Whether or not to show the `FilterOrdinalsModal` is a part of `BTCWalletProvider`. Initially I went with the `BTCWalletProvider` handling the "show/no show" the modal and `shouldFilterOrdinals` to be a part of `AppState`. But then we cannot just put the `FilterOrdinalsModal` inside this provider, since it has to consume `AppState` `shouldFilterOrdinals` commit: af8ea0bf8eda03f3ec21e30fec0e9aad621d7487

But then I switched to even simpler solution - filtering ordinals (modal, should show modal, should filter or not) is just a part of BTCWalletProvider. Commit: e366a752447fe88b5a161163c8efae16078e8c09

This solution provides us an easier way to manage the stuff. Also, as soon as this modal is a part of Tomo wallet connect, we can easier get rid of the modal itself, so as we will get Tomos internal "should filter ordinals or not"

2024-10-27 03:19 UTC, totraev requested changes

2024-10-27 03:19 UTC, totraev commented on src/app/hooks/api/useUTXOs.ts
>        address,
useUTXOs should be only responsible for fetching data (not filtering it). `filderOrdinals` method is a legacy

2024-10-27 03:19 UTC, totraev commented on src/app/context/wallet/BTCWalletProvider.tsx
> +  const [shouldFilterOrdinals, setShouldFilterOrdinals] = useState(true);
We need make wallet providers stateless, we moved all application's state to `/app/state` folder

2024-10-27 03:40 UTC, totraev requested changes

2024-10-27 03:40 UTC, totraev commented on src/app/context/wallet/BTCWalletProvider.tsx
> +      />
I don't think this modal relates to BTCWalletProvider. It can be placed anywhere inside our DApp

2024-10-27 03:52 UTC, totraev commented
If you want to place ordinal's logic inside `BTCWalletProvider` then you need modify `getUtxos` method cause currently it ignores your `shouldFilterOrdinals` flag and always return all UTXOs.

2024-10-29 01:46 UTC, totraev commented on src/app/state/index.tsx
> +  excludeOrdinals: () => void;
@jrwbabylonlab Yeah, it'll, but for now it's okay. We can decompose this context provider in the future (for performance optimisation reasons)

2024-10-29 01:46 UTC, totraev approved these changes

2024-10-29 05:08 UTC, gbarkhatov commented on src/app/state/index.tsx
> +  excludeOrdinals: () => void;
@jrwbabylonlab @totraev 
https://github.com/babylonlabs-io/simple-staking/issues/265

2024-10-29 05:16 UTC, gbarkhatov commented
Additional:
https://github.com/babylonlabs-io/simple-staking/issues/266

2024-10-29 05:16 UTC, merged