351 finality provider list UI
babylonlabs-io/simple-staking pull request #446
Opened 2024-12-04 10:16 UTC by jeremy-babylonlabs

2024-12-08 19:12 UTC, jeremy-babylonlabs commented
added fp list, pending a second look on https://github.com/babylonlabs-io/bbn-core-ui/pull/50
will double check and make this PR ready once that is merged.

2024-12-11 10:29 UTC, totraev requested changes
I'll need update this PR later

2024-12-11 10:29 UTC, totraev commented on src/app/components/Staking/FinalityProviders/FinalityProviderSubtitle.tsx
Do we really need this component?

2024-12-11 10:29 UTC, totraev commented on src/app/components/Staking/FinalityProviders/FinalityProviderTable.tsx
> +  );
move outside the rendering function

2024-12-11 10:29 UTC, totraev commented on src/app/components/Staking/FinalityProviders/FinalityProviderTable.tsx
> +  const { coinName } = getNetworkConfig();
move it outside the rendering function

2024-12-11 10:29 UTC, totraev commented on src/app/components/Staking/FinalityProviders/FinalityProviderTable.tsx
> +  const renderContent = () => {
You don't need this function

2024-12-11 10:29 UTC, totraev commented on src/app/components/Staking/FinalityProviders/FinalityProviderTitle.tsx
What is the purpose of this component?

2024-12-11 10:29 UTC, totraev commented on src/app/hooks/services/useFinalityProviderService.ts
> +export function useFinalityProviderServiceState() {
ServiceState ?

2024-12-11 10:29 UTC, totraev commented on src/app/state/FinalityProviderServiceState.tsx
I don't understand this

2024-12-12 06:10 UTC, jeremy-babylonlabs commented on src/app/state/FinalityProviderServiceState.tsx
my bad, my updated implementation was weirdly not included, resolved

2024-12-16 10:04 UTC, totraev approved these changes

2024-12-16 16:41 UTC, totraev approved these changes

2024-12-16 16:41 UTC, totraev commented on src/app/state/FinalityProviderState.tsx
> +      return [];
side effect inside useMemo function

2024-12-16 16:41 UTC, totraev commented on src/app/state/FinalityProviderState.tsx
> +    try {
why we need try/catch here?

2024-12-16 19:25 UTC, merged