feat: disable stake button if utxo not available
babylonlabs-io/simple-staking pull request #488
Opened 2024-12-10 05:18 UTC by jrwbabylonlab

<img width="653" alt="image" src="https://github.com/user-attachments/assets/975a4f97-09e4-49c8-8266-bb579e32ee69">

2024-12-11 10:05 UTC, totraev requested changes
Will update later today

2024-12-11 10:48 UTC, gbarkhatov approved these changes

2024-12-11 17:02 UTC, totraev requested changes

2024-12-11 17:02 UTC, totraev commented on src/app/state/index.tsx
> +  allUTXOs?: UTXO[];
@jrwbabylonlab it's not clear to me why do you use `allUTXOs` instead of `availableUTXOs`?

2024-12-11 18:35 UTC, totraev commented
> What need to be updated?

Don't write any domain specific logic inside render function directly. Use my fixes as a reference for future PRs

2024-12-11 18:36 UTC, totraev commented
@jrwbabylonlab can you pls check my changes? I didn't test them

2024-12-11 18:43 UTC, totraev commented
@jrwbabylonlab I see another problem: everytime we submit a staking tx we need invalidate utxos' cache and refetch them

2024-12-12 02:50 UTC, totraev commented on src/app/state/index.tsx
> +  allUTXOs?: UTXO[];
@jrwbabylonlab This is expected behaviour IMO. If user decided to filter out ordinals (to save them) we should not let him to stake his previously created delegation with ordinals

2024-12-12 03:42 UTC, totraev approved these changes

2024-12-12 03:43 UTC, totraev commented
@jrwbabylonlab approved, but pls test before merge

2024-12-12 05:40 UTC, merged