feat 526 signing modal improvement
babylonlabs-io/simple-staking pull request #550
Opened 2024-12-23 20:08 UTC by jeremy-babylonlabs

Blocked pending staking PR https://github.com/babylonlabs-io/simple-staking/pull/567

closes #526

2024-12-24 06:34 UTC, gbarkhatov approved these changes
Looks good, but I have an issue (maybe that's on my side):
https://i.imgur.com/UfQdASr.png and under that modal: https://i.imgur.com/AHdEjVM.png

2024-12-24 06:39 UTC, jeremy-babylonlabs commented
Ok I didn't catch this, thanks for pointing it out

2024-12-24 06:56 UTC, jeremy-babylonlabs commented
resolved

2024-12-25 04:49 UTC, totraev requested changes
I don't think that these changes make sense cause I completely refactored `staking.tsx` file. @jeremy-babylonlabs you need contact me regarding this PR

2024-12-25 04:49 UTC, totraev commented on src/app/components/Modals/PendingVerificationModal.tsx
> +          )}
Avoid of using double ternary operator, it's hard to read

2024-12-25 04:49 UTC, totraev commented on src/app/components/Modals/EOIModal/Step.tsx
> +  const isProcessing = state === "processing";
```suggestion
const ICONS: Record<StepProps["state"], ({ index }: { index: number }) => JSX.Element> = {
  completed: () => <IoCheckmarkSharp size={24} className="text-secondary-contrast" />,
  processing: () => <Loader size={24} className="text-secondary-contrast" />,
  upcoming: ({ index }) => <Text variant="body1" className="text-secondary-contrast">{index}</Text>
}
```
You can move this map from the component

2024-12-25 04:49 UTC, totraev commented on src/app/components/Modals/EOIModal/Step.tsx
> +        )}
```suggestion
        <Icon index={index} />
```

2025-01-03 04:45 UTC, merged